# .github/workflows/bump-version.yml
name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version bump (major, minor, patch):'
        required: true
        default: 'patch'

jobs:
  approve:
    name: Approve version bump
    environment: restricted
    runs-on: ubuntu-latest
    steps:
      - name: Request approval
        run: echo "Requesting approval for version bump"

  version-bump:
    name: Bump Version
    needs: approve
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to push tags
          token: ${{ secrets.BOT_PAT }}  # Authenticate as the bot - use a PAT with repo, workflow, and write:packages permissions for someone on the laser-actions team

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.BOT_PAT }}@github.com/${{ github.repository }}.git

      - name: Install bump-my-version
        run: python -m pip install bump-my-version

      - name: Bump version
        id: bump_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # may not be necessary since we are using a PAT
        run: |
          OLD_VERSION=$(grep '^version =' pyproject.toml | sed -E "s/.*= *[\"'](.*)[\"']/\1/")
          echo "OLD_VERSION=$OLD_VERSION" >> $GITHUB_ENV
          bump-my-version bump ${{ github.event.inputs.version_type }} --no-commit --no-tag
          NEW_VERSION=$(grep '^version =' pyproject.toml | sed -E "s/.*= *[\"'](.*)[\"']/\1/")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          git checkout -b version-bump-$NEW_VERSION
          git add --all
          git commit -m "Bump ${{ github.event.inputs.version_type }} version $OLD_VERSION -> $NEW_VERSION"
          git push --set-upstream origin version-bump-$NEW_VERSION

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Bump ${{ github.event.inputs.version_type }} version to ${{ steps.bump_version.outputs.new_version }}"
          branch: bump/version-${{ steps.bump_version.outputs.new_version }}
          title: "Bump ${{ github.event.inputs.version_type }} version to ${{ steps.bump_version.outputs.new_version }}"
          body: |
            Automated version bump PR.
          labels: |
            version-bump
          draft: false
          delete-branch: true
          # git tag "v$NEW_VERSION"
          # git push origin HEAD
          # git push origin --tags

      - name: Auto-approve PR
        if: steps.cpr.outputs.pull-request-number != ''
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.BOT_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.BOT_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: SQUASH